### ISSUE TITLE
import error: No module named 'src'

### ISSUE THREAD

**Issue by gecexgokyuzu** [iamdual/ua-generator#1]
![except](https://user-images.githubusercontent.com/103609940/165542948-e32a8437-0857-4eff-927c-92b909e28258.jpg)

i can call functions but whenever i run the app throws this exception, any idea why this might be happening?

**Comment by iamdual** [comment]
Did you use ua-generator via PIP package manager, or just cloned to your project?

**Comment by iamdual** [comment]
[Using relative imports](https://github.com/iamdual/ua-generator/commit/4ee85fc8e888cb36beb21d0201e0bb5e451f28ee) has solved this problem. Thank you for reporting.

Can you upgrade the package to 0.1.2?
```
pip3 install ua-generator --upgrade
```

**Comment by gecexgokyuzu** [comment]
works great!
