### ISSUE TITLE
Adding 'android' in the platform tuple breaks the generator

### ISSUE THREAD

**Issue by imcarlosguerrero** [iamdual/ua-generator#10]
**Describe the Bug**
Including 'android' in the `platform` tuple causes the user agent generator to raise an exception, preventing the program from running as expected.

**To Reproduce**
```python
import ua_generator

while(True):
    device = ('desktop', 'mobile')
    platform = ('windows', 'macos', 'ios', 'linux', 'android')
    browser = ('chrome', 'edge', 'firefox', 'safari')

    user_agent = ua_generator.generate(device=device, browser=browser, platform=platform)

    print(user_agent)
```

These parameters were taken from [here](https://github.com/iamdual/ua-generator?tab=readme-ov-file#customization).

**Expected Behavior**
The script should generate an infinite loop of random user agent strings, including those for Android devices, without any errors.

**Actual Behavior**
When the `platform` tuple contains 'android' and this is randomly selected for the generation process, the generator raises a CannotGenerateError exception and terminates the script.

**Error Logs**
`File "C:\Users\username\AppData\Local\Programs\Python\Python311\Lib\site-packages\ua_generator\data\generator.py", line 177, in __user_agent
    raise exceptions.CannotGenerateError(self)
ua_generator.exceptions.CannotGenerateError: <ua_generator.data.generator.Generator object at 0x000001FA5ADD8D90>
`

**Workaround**
Removing 'android' from the `platform` tuple allows the generator to function correctly, but this limits the generation of user agents for Android devices.

**Environment**
- **Python Version**: 3.11
- **Package Version**: 1.0.0
- **OS**: Windows

**Additional Context**
This issue seems to occur only when 'android' is included in the `platform` tuple, indicating a potential problem with the generator's handling of the Android platform.

**Comment by gaby** [comment]
It happens or used to happen with iOS too. It has something to do because having all of those will trigger some combinations that are not compatible, for example Safari + Android. It's not a new issue in v1.0.0

@iamdual

**Comment by imcarlosguerrero** [comment]
> It's not a new issue in v1.0.0

You mean that I should close this in favour of another issue? In that case, which one?

**Comment by gaby** [comment]
@imcarlosguerrero Leave it open, I noticed this issue last week before the release of v1.0.0 so it's an actual issue

**Comment by iamdual** [comment]
Thank you all for the report.

I quickly fixed the issue with a [commit](https://github.com/iamdual/ua-generator/commit/a780538b2133b4cf4bc8efcada643e089af4ea41). The cause of the issue is the selection of both the `desktop` device and the `android` platform together. As you can see in the commit, I removed the `self.device == 'mobile'` part. This was a forward-thinking approach, but it caused a crash. 

It actually has no relation to v1.0.0. The same issue was present in earlier versions as well. Version 1.0.0 only included structural changes and new implementations.

With v1.0.1, the issue has been fixed.

**Comment by gaby** [comment]
@iamdual Thank you, I will test today on my side. 💪

**Comment by imcarlosguerrero** [comment]
It seems like it's working correctly now, I'm closing the issue as this has been solved. Thanks, @iamdual for the fix.
