### ISSUE TITLE
Add an option to choose browser version from array

### ISSUE THREAD

**Issue by barakolshe** [iamdual/ua-generator#6]
Can you please add an option to choose a browser version from an array of options

**Comment by krishgalani** [comment]
Hey man, I see this case is still open, I have forked the repo and am ready to contribute to implement this feature. Would you still like that?

**Comment by iamdual** [comment]
> Hey @iamdual , I see this case is still open, I have forked the repo and am ready to contribute to implement this feature. Can I go ahead?

Feel free to make the changes if you'd like. 

I also had plans to make some related changes about this, but I haven't had the time to look into all of them yet. So far, I've only implemented the "[weighted versions](https://github.com/iamdual/ua-generator/commit/575fb120ad2563debc3c03c61a49cbd8108d2324)" feature, but it still needs to be tested.
