### ISSUE TITLE
test_contains_multiple

### ISSUE THREAD

**Issue by krishgalani** [iamdual/ua-generator#9]
what is the point of contains_multiple in utils.py, is it a check if the input tuple (t) or string is a subset of the arr provided? In that case why is the second test_case assert true?

**Comment by iamdual** [comment]
The purpose of the `contains` function is to check whether the given value is contained within any of the types (string, tuple, or list). However, the second parameter only accepts string. The other function `contains_multiple` serves the same purpose, with the only difference being that the second parameter can accept tuple and list.

It's useful for validating user inputs and hasn't caused any issues so far :)

**Comment by krishgalani** [comment]
If this is true, then the contains_multiple function isn't doing what you specified. Since the function returns True upon the _first_ value found to be in arr.

**Comment by iamdual** [comment]
Yes, good catch, thanks for your suggestion. New implementation in [here](https://github.com/iamdual/ua-generator/commit/4337dce0d4f855fbf11269a0f206208cff9617f2).
